version: "2.1"

volumes:
  minio_data:
    driver: local

services:
  postgres:
    container_name: wt_testing_pg
    hostname: postgres
    # image: postgres:12
    image: postgres:10
    restart: "no"
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pa55w0rd
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
      - 54321:5432

  minio:
    container_name: minio
    hostname: minio
    image:  docker.io/bitnami/minio:2021
    environment:
      - MINIO_ROOT_USER=DEVDEVDEV001
      - MINIO_ROOT_PASSWORD=DEVDEVDEV001
      - MINIO_DEFAULT_BUCKETS=my-first-bucket,my-second-bucket
      - MINIO_CONFIG_DIR=/minio_config
    volumes:
      - minio_data:/data
      - ./minio_config:/minio_config
    ports:
      - 9000:9000
      - 9001:9001

  setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 20;
      /usr/bin/mc config host add myminio http://minio:9000 DEVDEVDEV001 DEVDEVDEV001;
      /usr/bin/mc rm -r --force myminio/somebucketname;
      /usr/bin/mc mb myminio/somebucketname;
      /usr/bin/mc policy download myminio/somebucketname;
      exit 0;
      "
